name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # ---- Docker Login ----
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---- Build & Push FRONTEND ----
      - name: Build Frontend Image
        run: |
          docker build -t nadimhassan02/oslab-frontend:latest ./lab_6/frontend
          docker push nadimhassan02/oslab-frontend:latest

      # ---- Build & Push BACKEND ----
      - name: Build Backend Image
        run: |
          docker build -t nadimhassan02/oslab-backend:latest ./lab_6/backend
          docker push nadimhassan02/oslab-backend:latest

      # ---- Build & Push DB ----
      - name: Build DB Image
        run: |
          docker build -t nadimhassan02/oslab-db:latest ./lab_6/db
          docker push nadimhassan02/oslab-db:latest
